language: node_js

before_install:
  npm install -g yarn

node_js:
  - "10"
  - "8"
  - "6"

cache:
  directories: 
    - node_modules/
    - ~/.npm

install:
  - yarn

script:
  - yarn flow status
  - yarn lint
  - commitlint-travis
  # - yarn test
